### PR TITLE
Add multitouch support (fixes #8)

### LINKED ISSUE #8: The joystick needs multitouch support.
This asset is awesome, it deserves the multitouch support to be the main.

### PR DESCRIPTION
**Pull request by eastolfi**
Hi!

So, I've been looking the last few days for a solution to implement an in-screen joystick and button, but I had some problems with the examples found because of relative/global positions (they were based in Node2D childs).
So then I found yours, which is awesome and with a lot of options. But is currently lacking the multi-touch support (as reported [here](#8 ))

I decided then to try and implement a solution for this. The cause **I think** is in the *_gui_ui* event, which doesn't handle the multiple touches. I had to change the logic to the *_input* and add some controls to verify if the event is in the rect area and stuff like that.
I ended using a "custom" scene based heavily on your idea, with quite a nice refactor.

Anyway, I tried to pull out some of the changes on your solution to implement the multi touch. You're free to review them, discuss about them, and make any change you want, or close this PR ir you decides so.

Thanks for the nice work in any case 👍

### CODE REVIEW

**Comment by qarlosh** [comment]
I just tested this and works great. Now I can use a `Joystick` and a `TouchScreenButton` using two fingers, without interfering.
Tested in Android (Samsung Galaxy S8).

**Comment by qarlosh** [comment]
After some more testing, I've noticed that the joystick handle is off-center. I attach a gif to better show the issue:
ezgif com-video-to-gif
It is more noticeable in a touchscreen - when you touch the joystick in the center it moves to the down-right direction.
It doesn't happen in the original.

**Comment by eastolfi** [comment]
Hi! Yeah, working with positions for this is a bit annoying. I the test scene I did not have this problem, but I started to mess around with the scales, and I had the same problem.

I made a few changes and I now everything should works fine.

**Comment by qarlosh** [comment]
thank you! I will try it when I have a moment

**Comment by qarlosh** [comment]
I still have the same problem. As you said, it is related to scaling. When the `Joystick` parent is scaled, the handle position is off-center.
In my project I've a script to scale the input interface to the screen size. I tried to change only the joystick position without scaling, but then the size depends on the device screen resolution, resulting in a very small joystick. I think that it is necessary to be able to scale the Joystick.

**Pull request merged**
