### PR TITLE
Port to Godot 4

### PR DESCRIPTION
**Pull request by justofisker**
This pull request fully ports this project to Godot 4. It also documents all of the member, methods, and enums of `VirtualJoystick`. I wrote a few of them and just reused comments as documentation in some cases. Hope you consider merging this pull request. Thank you for your time 😺

### CODE REVIEW

**Comment by justofisker** [comment]
Fixes #34

**Comment by justofisker** [comment]
Unsure if merging this into main is a good idea as it'll cause conflict with 3.x users from the asset library. Probably best to create a new branch in which to place this if you want to accept this pull request. Thank you for your time :)

**Comment by justofisker** [comment]
Updated to 4.0 release candidate 1 (there should be no breaking changes in Godot from now)

**Comment by MarcoFazioRandom** [comment]
Updated to Godot 4.0. 
sorry for the late update.

**Pull request closed without merging**
